### ISSUE TITLE
duo-pinmux does not run

### ISSUE THREAD

**Issue by skarstein** [johandevlabs/milk-v-duo-s-notes#1]
Hey great work on this. I'm trying to follow along with the I2C section but I'm stuck on this step:

> Copy duo-pinmux and ld-musl-riscv64v0p7_xthead.so.1 from the latest Milk V buildroot (1.2) image (/usr/bin/duo-pinmux and /lib/ld-musl-riscv64v0p7_xthead.so.1), to the corresponding debian folders
> Run duo-pinmux and see correct pinout

I copied the buildroot version of duo-pinmux onto my board but it cannot execute:
```
debian@duos:~$ sudo ./duo-pinmux -p
sudo: unable to execute ./duo-pinmux: Permission denied
```

You can see full permissions here so I don't think that's the issue:
```
debian@duos:~$ ls -ll | grep pinmux
-rwxrwxr-x 1 debian debian  32992 Aug 29 22:00 duo-pinmux
```

Here is the file details. Seems ok to me:
```
debian@duos:~$ file duo-pinmux
duo-pinmux: ELF 64-bit LSB pie executable, UCB RISC-V, RVC, double-float ABI, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-riscv64v0p7_xthead.so.1, with debug_info, not stripped
```

I grabbed the `duo-pinmux` executable directly from the board while I still had buildroot running on it. Should I have taken from elsewhere? Have you run into this type of error running on your debian image before?

Any insight is appreciated, thanks!

**Comment by johandevlabs** [comment]
Hi @skarstein ,

It is odd that you cant execute it with sudo. Have tried signing in as root and running it directly?

I also noticed that your `duo-pinmux` file size is a bit different from mine. On my system:
```
debian@duos:~$ ls -ll start-up-scripts/duo-pinmux 
-rwxr-xr-x 1 debian debian 27424 Aug 16 09:17 start-up-scripts/duo-pinmux

debian@duos:~$ file start-up-scripts/duo-pinmux 
start-up-scripts/duo-pinmux: ELF 64-bit LSB pie executable, UCB RISC-V, RVC, double-float ABI, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-riscv64v0p7_xthead.so.1, stripped

debian@duos:~$ ls -ll /lib/ld-musl-riscv64v0p7_xthead.so.1 
-rwxr-xr-x 1 root root 572064 Aug 16 09:32 /lib/ld-musl-riscv64v0p7_xthead.so.1
```
Note, I placed the Buildroot duo-pinmux in `/home/debian/start-scripts` folder and executed it from there with sudo. I have also created a service that runs on boot that sets the pin mode for the i2c-4 pins so I don't have to do it everytime I boot.

I am attaching the duo-pinmux executable and ld-musl-riscv64v0p7_xthead.so.1 I used for reference
[duo-pinmux-files.zip](https://github.com/user-attachments/files/16812835/duo-pinmux-files.zip)

**Comment by skarstein** [comment]
After digging around for a long time I managed to figure this out. Turns out when I copy executables from my windows host machine (PowerShell) over scp, the device cannot execute them. However, if I scp the same file from my WSL environment it executes fine. No idea why but I'm glad I've got it working.

I do wonder why there are only three out of the four i2c devices visible. I was planning on using i2c-1 for this device but i2c-2 works just as well.

After I got that working I was able to import the wiringx library which came with the buildroot image for easy i2c/gpio control in C. Just copy the library and header from the buildroot release onto the corresponding directories on your device:
```
/usr/lib/libwiringx.so
/usr/include/wiringx.h
```
Then you can basically follow the directions here for I2C/SPI/PWM etc: https://milkv.io/docs/duo/application-development/wiringx

I managed to get a small application to read from a max17048 fuel gauge over i2c:
```
debian@duos:~$ sudo ./max17048
max17048 i2c test
Successfully found max17048 with chip ID: 0C
ic version: 0x12
chargeRatePercentHr: 0.000000 percent per hour
Battery voltage: 3.816250 V
Battery percentage 44.050781 %
```

But anyway I managed to fix the original issue I described here so I'll go ahead and close this. Thanks again for your help!

**Comment by johandevlabs** [comment]
OK, I am glad that you figured it out. 

I will take a look at wiringx!

Thank you
